package SpringBoot.College_Management.Security_Section.Enums;

public enum Permissions {


    USER_VIEW,
    USER_CREATE,
    USER_UPDATE,
    USER_DELETE,

    STUDENT_VIEW,
    STUDENT_CREATE,
    STUDENT_UPDATE,
    STUDENT_DELETE,

    PROFESSOR_VIEW,
    PROFESSOR_CREATE,
    PROFESSOR_UPDATE,
    PROFESSOR_DELETE,

    COURSE_VIEW,
    COURSE_CREATE,
    COURSE_UPDATE,
    COURSE_DELETE,

    DEPARTMENT_VIEW,
    DEPARTMENT_CREATE,
    DEPARTMENT_UPDATE,
    DEPARTMENT_DELETE,

    SUBJECT_VIEW,
    SUBJECT_CREATE,
    SUBJECT_UPDATE,
    SUBJECT_DELETE

}